apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTlRNME1Ea3lPVGd3SGhjTk1qVXdOekkxTURJd09ERTRXaGNOTXpVd056SXpNREl3T0RFNApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTlRNME1Ea3lPVGd3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSanlDTzZDTlY4aFVaTG5hYmI2QXZSekY5UDdVVU16aVgvZ0lGVWlsamcKbkQ5RERsQ0RzWWNCb1FwSjRUbHVQN2hyZGdqdDdwNUdNbDYxOCtUSVdrcG9vMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXVzb0p1VlVFZHpVZmUySXZpaTVpCndUKzJFZFl3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnS0VwQ2lTNC9RZ3FodmorSHg5NFhlemRqUnE1Y25ZRUcKNUZWNndDNVRaaElDSVFEUmFpdFJjbjF3OFZvR1dBaEExTjIrM0tPdm9QQmZ6RzRKV1p6YmRBdFQ1UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://a0b221e57815.ngrok-free.app
  name: k3d-mycluster
contexts:
- context:
    cluster: k3d-mycluster
    user: admin@k3d-mycluster
  name: k3d-mycluster
current-context: k3d-mycluster
kind: Config
preferences: {}
users:
- name: admin@k3d-mycluster
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJSndMcnRUK0lhZG93Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOelV6TkRBNU1qazRNQjRYRFRJMU1EY3lOVEF5TURneE9Gb1hEVEkyTURjeQpOVEF5TURneE9Gb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJOVDBaTTNDYTdBZFBBWTcKM0J3akxhaWtLd0F5eHF6R0xEazJGYWlhT0lKdWR4bVRFZHNxZW4vWUZ6YzZGc2I3bk05WUFLSTI0MHZEK1lDUgptbHhaNk5xalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCVFdXNFpFZmlzY1VVTDkvYnNNSWRCdi9BOGEvakFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlFQXNBRTJtbjZ6SGhVL0VUOUtQRE1HdUNJMkdmRnhWNnp4SEJlL3NzQmlGcEVDSUFnRG5PMlNlb1pkaGNPQwpOK3htejJ5VDNZSWdsaDBpNDh5bFMwMjc3WHNSCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUkvZDBUSXZDV1dGYjRWTXVUd1JUOUJRbElhT1FEOEZIUUordWpOQlFxTjNvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFMVBSa3pjSnJzQjA4Qmp2Y0hDTXRxS1FyQURMR3JNWXNPVFlWcUpvNGdtNTNHWk1SMnlwNgpmOWdYTnpvV3h2dWN6MWdBb2pialM4UDVnSkdhWEZubzJnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
