name: Build & Deploy to K3d

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/random-word-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/random-word-app:latest

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config

      - name: Update image in deployment
        run: |
          kubectl set image deployment/random-word-deployment random-word-container=${{ secrets.DOCKER_USERNAME }}/random-word-app:latest --insecure-skip-tls-verify --validate=false

